from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")


containerized: "docker://ghcr.io/ht-diva/harmonization_pipeline:6475c06"


configfile: "config/config.yaml"


include: "rules/common.smk"


if config.get("run").get("harmonization"):

    include: "rules/harmonization.smk"

elif config.get("run").get("gwascatalog"):

    include: "rules/gwascatalog_harmonization.smk"

elif config.get("run").get("liftoverbcf_harmonization"):

    include: "rules/liftoverbcf_harmonization.smk"
    
elif config.get("run").get("pre_filtering_and_harmonization"):

    include: "rules/pre_filtering_and_harmonization.smk"

else:

    include: "rules/post_filtering_and_harmonization.smk"

if config.get("run").get("to_parquet"):

    include: "rules/to_parquet.smk"

include: "rules/summarize.smk"


if config.get("run").get("delivery"):

    include: "rules/delivery.smk"


rule all:
    input:
        get_final_output(),
    resources:
        runtime=3,
