---
# common parameters
n_cores: &cores 8

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'basic_check'
  - 2: 'infer_build'
  - 3: 'fill_data'
  - 4: 'liftover'
  - 5: 'harmonize'
  - 6: 'sort_alphabetically'
  - 7: 'write_snp_mapping'

steps:
  basic_check: # see https://cloufield.github.io/gwaslab/Standardization/
    params:
      run: True
    gl_params:
      n_cores: *cores
      normalize: True
      fixid_args:
        fixid: True
        overwrite: True
  infer_build: # see https://cloufield.github.io/gwaslab/InferBuild/
    params:
      run: True
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    params:
      run: True
    gl_params:
      to_fill: [ 'MLOG10P' ]
      overwrite: False
      extreme: True
  harmonize: # see https://cloufield.github.io/gwaslab/Harmonization/
    params:
      run: True
    gl_params:
      basic_check: True
      n_cores: *cores
  liftover: # see https://cloufield.github.io/gwaslab/LiftOver/
    params:
      run: True
    gl_params:
      n_cores: *cores
      from_build: "19"
      to_build: "38"
      remove: True
  sort_alphabetically:
    params:
      run: True
    gl_params:
      n_cores: *cores
  write_snp_mapping: # see https://cloufield.github.io/gwaslab/Standardization/
    params:
      run: True
      workspace: "snp_mapping"
      workspace_subfolder: False
    gl_params:
      fmt: "snp_mapping"

# Filename transformation, e.g.: 2025_05_13_eGFR.min_singlevariant51kGSA-TOPMEDr3-GWAS_eGFR.min.regenie.gz
filename_mask: [ True, True, True, False, False]

# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: "workflow/scripts/gwaspipe/data/formatbook.json"     # fill this var if you want to provide a custom formatbook
