run:
  pre_filtering_and_harmonization: False
  harmonization: True
  harmonization_and_post_filtering: False
  summarize: True
  delivery: True


# Paths
# test: config/small_test_believe.tsv
# full: config/sumstats_from_believe.tsv
snpid2filter: "/scratch/giulia.pontali/believe/prob_snps/problematic_snps.txt"
sumstats_path: config/sumstats_from_believe.tsv
sumstats_suffix: ".fastGWA" # Suffix of input summary statistics files (check in sumstats_path)
input_snpid_col: "SNP" # Input SNPID column name (check in sumstats_path)
filter_snpid_col: "ID" # Column name for filtering (check in snpid2filter)
dest_path: "/project/cdh/believe/result"
workspace_path: ../results
sumstats_sep: "\t"

# Common parameters
input_format: &iformat "fastgwa" # Input format of summary

params:
  harmonize_sumstats:
    input_format: *iformat
    config_file: "config/config_harmonize_sumstats.yml"
  harmonize_sumstats_pre_filtering:
    config_file: "config/config_harmonize_sumstats_pre_filtering.yml"
  harmonize_sumstats_post_filtering:
    config_file: "config/config_harmonize_sumstats_post_filtering.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  snp_mapping:
    input_format: *iformat
    config_file: "config/config_snp_mapping.yml"
