run:
  pre_filtering_and_harmonization: True
  harmonization: False
  harmonization_and_post_filtering: False
  summarize: True
  delivery: False


# paths
# note for sumstats_path:
# test: config/small_test_chris.tsv
# full: config/seqid_from_chris.tsv
# orig_full: /scratch/gianmauro.cuccuru/pqtl_pipeline/chris_23_09_2024/config/seqid_CHRIS_full_list.txt
# sumstats at: /exchange/healthds/pQTL/CHRIS/summary_stats/raw/alias/
snpid2filter: "/exchange/healthds/pQTL/results/CHRIS/infoscore_HRC_pQTL_harmonized_snpid.csv"
sumstats_path: config/small_test_chris.tsv
sumstats_suffix: ".regenie.gz" # Suffix of input summary statistics files (check in sumstats_path)
input_snpid_col: "ID" # Input SNPID column name (check in sumstats_path)
filter_snpid_col: "SNPID" # Column name for filtering (check in snpid2filter)
dest_path: destination
workspace_path: results


params:
  harmonize_sumstats:
    input_format: "regenie"
    config_file: "config/config_harmonize_sumstats.yml"
  harmonize_sumstats_pre_filtering:
    config_file: "config/config_harmonize_sumstats_pre_filtering.yml"
  harmonize_sumstats_post_filtering:
    config_file: "config/config_harmonize_sumstats_post_filtering.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  snp_mapping:
    input_format: "regenie"
    config_file: "config/config_snp_mapping.yml"
