# Rule execution flags
run:
  harmonization: False
  liftoverbcf_harmonization: False
  gwascatalog: True
  summarize: True
  delivery: True


# Paths
sumstats_path: config/sumstats_from_gwascatalog.tsv
sumstats_url: config/urls_gwascatalog_test.tsv
sumstats_suffix: ".h.tsv.gz" # Suffix of input summary statistics files (check it in the sumstats_path list)
sumstats_sep: "\t"
dest_path: "../destination"
workspace_path: "../results"
hg37_fasta_file_path: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta'
hg38_fasta_file_path: '/group/diangelantonio/public_data/liftOver/hg38.fa'
chain_file_path: '/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz'

# Common parameters
input_format: &iformat "gwascatalog_hm" # Input format of summary (not used here; inferred from data columns)

params:
  harmonize_sumstats:
    input_format: *iformat
    config_file: "config/config_harmonize_sumstats.yml"
  snp_mapping:
    input_format: *iformat
    config_file: "config/config_snp_mapping.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  to_vcf:
    input_format: *iformat
    config_file: "config/config_to_vcf.yaml"
  harmonize_sumstats_pre_filtering:
    config_file: "config/config_harmonize_sumstats_pre_filtering.yml"
  harmonize_sumstats_post_filtering:
    config_file: "config/config_harmonize_sumstats_post_filtering.yml"
