set-resources:
  pre_filtering:
    job_name: "pre_filtering"
    mem_base: 22528
    mem_per_attempt: 2048
    runtime_per_attempt: 30
  harmonize_sumstats:
    job_name: "pre_filtering"
    mem_base: 22528
    mem_per_attempt: 2048
    runtime_per_attempt: 60
  post_filtering:
    job_name: "post_filtering"
    mem_base: 22528
    mem_per_attempt: 2048
    runtime_per_attempt: 30
  summarize_sumstats:
    job_name: "summarize_sumstats"
    mem_base: 22528
    mem_per_attempt: 2048
    runtime_per_attempt: 60
#  annotate_sumstats:
#    job_name: "annotate_sumstats"
#    mem_base: 18432
#    mem_per_attempt: 2048
#    runtime_per_attempt: 
  bgzip_tabix:
    job_name: "bgzip_tabix"
    mem_base: 512
    mem_per_attempt: 512
    runtime_per_attempt: 10
  create_if_table:
    job_name: "create_if_table"
    mem_base: 512
    mem_per_attempt: 512
    runtime_per_attempt: 5
  create_min_pvalue_table:
    job_name: "create_min_pvalue_table"
    mem_base: 512
    mem_per_attempt: 512
    runtime_per_attempt: 5
  create_snp_mapping_table:
    job_name: "create_snp_mapping_table"
    mem_base: 22528
    mem_per_attempt: 2048
    runtime_per_attempt: 60
  sync_tables:
    job_name: "sync_tables"
    mem_base: 1024
    mem_per_attempt: 1024
    runtime_per_attempt: 10
  sync_plots:
    job_name: "sync_plots"
    mem_base: 1024
    mem_per_attempt: 1024
    runtime_per_attempt: 30
  sync_outputs_folder:
    job_name: "sync_outputs_folder"
    mem_base: 1024
    mem_per_attempt: 1024
    runtime_per_attempt: 60
