---
# common parameters
n_cores: &cores 3

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'fill_data'
  - 2: 'write_metal'

steps:
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    params:
      run: True
    gl_params:
      to_fill: ['P', 'Z']
      overwrite: False
      extreme: False
  write_metal:
    params:
      run: True
      workspace: "metal"
      workspace_subfolder: True
    gl_params:
      fmt: "metal"

# Filename transformation, e.g.: seq.3007.7.gwas.regenie.gz
filename_mask: [ True, True, True, False ]
filename_sep: '.'

# IO
root_path: "results"
log_filename: "gwaspipe.log"
report_if_filename: "report_if_placeholder.txt"
formatbook_path: " "     # fill this var if you want to provide a custom formatbook
