---
# common parameters
n_cores: &cores 4

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'write_vcf'

steps:
  write_vcf:
    params:
      run: True
      workspace: "vcf"
      workspace_subfolder: True
    gl_params:
      fmt: "vcf"
      bgzip: True
      tabix: True
      tabix_indexargs:
        'csi': True
      build: "19"

# Filename transformation, e.g.: seq.3007.7.gwas.regenie.gz
filename_mask: [ True, True, True, False ]
filename_sep: '.'

# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: " "     # fill this var if you want to provide a custom formatbook
