---
# common parameters
n_cores: &cores 4

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'fill_data'
  - 2: 'report_min_pvalue'

steps:
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    params:
      run: True
    gl_params:
      to_fill: ['MLOG10P', 'Z']
      overwrite: False
      extreme: True
  report_min_pvalue:
    params:
      run: True
      workspace: "min_P"


# Filename transformation, e.g.: seq.3007.7.gwas.regenie.gz
filename_mask: [ True, True, True, False ]
filename_sep: '.'


# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: " "     # fill this var if you want to provide a custom formatbook
