run:
  harmonization: False
  liftoverbcf_harmonization: True
  summarize: True
  delivery: True


# Paths
# test: config/small_test_meta_chris_interval.tsv
# full: config/sumstats_from_meta_chris_interval.tsv
sumstats_path: config/sumstats_from_meta_chris_interval.tsv
sumstats_suffix: ".sorted.filtered.TBL" # Suffix of input summary statistics files (check in sumstats_path)
dest_path: "/project/cdh/meta_chris_interval/results"
workspace_path: ../results
sumstats_sep: "\t"
hg37_fasta_file_path: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta'
hg38_fasta_file_path: '/group/diangelantonio/public_data/liftOver/hg38.fa'
chain_file_path: '/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz'

# Common parameters
input_format: &iformat "metal_het" # Input format of summary

params:
  harmonize_sumstats:
    input_format: "vcf"
    config_file: "config/config_harmonize_sumstats.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  snp_mapping:
    input_format: "vcf"
    config_file: "config/config_snp_mapping.yml"
  to_vcf:
    input_format: *iformat
    config_file: "config/config_to_vcf.yaml"
