---
# common parameters
n_cores: &cores 4

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'basic_check'
  - 2: 'infer_build'
  - 3: 'write_vcf'


steps:
  basic_check: # see https://cloufield.github.io/gwaslab/Standardization/
    params:
      run: True
    gl_params:
      n_cores: *cores
      normalize: True
  infer_build: # see https://cloufield.github.io/gwaslab/InferBuild/
    params:
      run: True
  write_vcf:
    params:
      run: True
      workspace: "temp"
      workspace_subfolder: True
      study_name_mask: [ True, True, True ]
      study_name_sep: '.'
    gl_params:
      fmt: "vcf"


# Filename transformation, e.g.: seq.3007.7.gwas.regenie.gz
filename_mask: [ True, True, True, False, False, False]
filename_sep: '.'

# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: "workflow/scripts/gwaspipe/data/formatbook.json"     # fill this var if you want to provide a custom formatbook