run:
  harmonization: True
  summarize: True
  delivery: True


# Paths
# test: config/small_test_finngen.tsv
# full: config/sumstats_from_finngen.tsv
sumstats_path: config/sumstats_from_finngen.tsv
sumstats_suffix: ".gz" # Suffix of input summary statistics files (check in sumstats_path)
dest_path: "/project/cdh/finngen/results"
workspace_path: ../results
sumstats_sep: "\t"

# Common parameters
input_format: &iformat "finngen" # Input format of summary

params:
  harmonize_sumstats:
    input_format: *iformat
    config_file: "config/config_harmonize_sumstats.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  snp_mapping:
    input_format: *iformat
    config_file: "config/config_snp_mapping.yml"
