run:
  pre_filtering_and_harmonization: False
  harmonization: True
  harmonization_and_post_filtering: False
  summarize: True
  delivery: True


# Paths
# test: config/small_test_interval.tsv
# full: config/seqid_from_interval.tsv
snpid2filter: "/exchange/healthds/pQTL/results/CHRIS/infoscore_HRC_pQTL_harmonized_snpid.csv"
sumstats_path: config/seqid_from_interval.tsv
sumstats_suffix: ".gwas.regenie.gz" # Suffix of input summary statistics files (check in sumstats_path)
input_snpid_col: "ID" # Input SNPID column name (check in sumstats_path)
filter_snpid_col: "SNPID" # Column name for filtering (check in snpid2filter)
dest_path: "/project/cdh/interval/result"
workspace_path: ../results
sumstats_sep: "\t"

# Common parameters
input_format: &iformat "regenie" # Input format of summary

params:
  harmonize_sumstats:
    input_format: *iformat
    config_file: "config/config_harmonize_sumstats.yml"
  harmonize_sumstats_pre_filtering:
    config_file: "config/config_harmonize_sumstats_pre_filtering.yml"
  harmonize_sumstats_post_filtering:
    config_file: "config/config_harmonize_sumstats_post_filtering.yml"
  summarize_sumstats:
    input_format: "gwaslab"
    config_file: "config/config_summarize_sumstats.yml"
  snp_mapping:
    input_format: *iformat
    config_file: "config/config_snp_mapping.yml"
