name: Docker

on:
  push:
    branches: [ "main", "clean_up" ] # TO DO: ["main"]
    paths:
      - 'Dockerfile'
      - 'workflow/envs/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      # TO DO: uncomment
      # Workaround: https://github.com/docker/build-push-action/issues/461
      #- name: Setup Docker buildx
      #  uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      #- name: Log into registry ${{ env.REGISTRY }}
      #  if: github.event_name != 'pull_request'
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      #- name: Build and push Docker image
      #  id: build-and-push
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHORT_SHA }}
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max

      # Update git commit SHA in Snakefile for new image
      - name: Update git commit SHA in Snakefile
        run: |
          sed 's/pqtl_pipeline:.*/pqtl_pipeline:${{ env.COMMIT_SHORT_SHA }}"/' $GITHUB_WORKSPACE/workflow/Snakefile > $GITHUB_WORKSPACE/tmp
          mv $GITHUB_WORKSPACE/tmp $GITHUB_WORKSPACE/workflow/Snakefile
      
      # Check for missing lines in Dockerfile and in case add them
      - name: Check for missing Dockerfile lines
        run: |
          grep -qxF "ENV DEBIAN_FRONTEND=noninteractive" $GITHUB_WORKSPACE/Dockerfile || sed '/# Step 1: Retrieve conda environments/i\
          ENV DEBIAN_FRONTEND=noninteractive\
          RUN apt update && apt install -y build-essential libz-dev && rm -rf /var/lib/apt/lists/*\
          \
          ' $GITHUB_WORKSPACE/Dockerfile > $GITHUB_WORKSPACE/tmp
          grep -qxF "ENV DEBIAN_FRONTEND=noninteractive" $GITHUB_WORKSPACE/Dockerfile || mv $GITHUB_WORKSPACE/tmp $GITHUB_WORKSPACE/Dockerfile

      # Set Git config with default GitHub Actions bot user
      - name: Set Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit changes to the Snakefile
      # TO DO: git push origin main
      - name: Commit Snakefile changes
        run: |
          git add $GITHUB_WORKSPACE/workflow/Snakefile
          git add $GITHUB_WORKSPACE/Dockerfile
          git commit -m "Updated Snakefile with new container tag"
          git push origin clean_up